export const FETCH_BEERS_SAGA = "FETCH_BEERS_SAGA"
export const RECEIVED_BEER_DATA = "RECEIVED_BEER_DATA"
export const FETCH_BEERS_SUCCESS = "FETCH_BEERS_SUCCESS"
export const FETCH_BEERS_FEILD = "FETCH_BEERS_FEILD"

export const UPDATE_FAVLSIT = "UPDATE_FAVLSIT"
export const UPDATE_FAVLSIT_BY_SAGA = "UPDATE_FAVLSIT_BY_SAGA"
export const POPUP_BEER = "POPUP_BEER"